apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: emeth-staging

resources:
  - ../../resources
  - routes.yaml

patches:
  - path: pull.patch.yaml
    target:
      kind: Deployment
      labelSelector: "app.kubernetes.io/name=emeth"

configMapGenerator:
  - name: config
    envs:
      - .env

secretGenerator:
  - name: secret
    envs:
      - .env.local
